### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to initialize OXM.qcom.video.encoder.avc, error 0xfffffffe

### ISSUE THREAD

**Issue by uu993** [yrom/ScreenRecorder#23]
代码报错，解析不了格式

java.lang.IllegalArgumentException: Failed to initialize OXM.qcom.video.encoder.avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1776)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
        at net.yrom.screenrecorder.BaseEncoder.createEncoder(BaseEncoder.java:112)
        at net.yrom.screenrecorder.BaseEncoder.prepare(BaseEncoder.java:80)
        at net.yrom.screenrecorder.ScreenRecorder.prepareVideoEncoder(ScreenRecorder.java:402)
        at net.yrom.screenrecorder.ScreenRecorder.record(ScreenRecorder.java:202)
        at net.yrom.screenrecorder.ScreenRecorder.access$000(ScreenRecorder.java:42)
        at net.yrom.screenrecorder.ScreenRecorder$CallbackHandler.handleMessage(ScreenRecorder.java:150)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:185)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yrom** [comment]
选择不同的codec再试试
