### ISSUE TITLE
小米9录制Crash

### ISSUE THREAD

**Issue by wangliang0209** [yrom/ScreenRecorder#38]
OS Version: 9_28
Vendor: Xiaomi
Model: MI 9
CPU ABI: armeabi-v7a

java.lang.IllegalStateException: writeSampleData returned an error
 at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
 at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:682)
 at com.wl.screenrecorder.ScreenRecorder.writeSampleData(ScreenRecorder.java:287)
 at com.wl.screenrecorder.ScreenRecorder.signalEndOfStream(ScreenRecorder.java:176)
 at com.wlscreenrecorder.ScreenRecorder.access$300(ScreenRecorder.java:42)

**Comment by yrom** [comment]
有其它的日志吗，logcat里

**Comment by zxjrainbow** [comment]
啊。没注意啊。。你突然一个邮件，我都差点忘了这事了。
加个QQ？ 3980599。



zxjrainbow@9ele.com
 
发件人： Yrom Wang
发送时间： 2019-07-23 11:27
收件人： yrom/ScreenRecorder
抄送： Subscribed
主题： Re: [yrom/ScreenRecorder] 小米9录制Crash (#38)
有其它的日志吗，logcat里

**Comment by NoahZu** [comment]
我用这个项目改造了一下 也遇到这个问题了，经过我的调试，发现是在MediaMuxer 调用writeSampleData的时候写入的音频数据的时间戳有问题，出现了新的时间戳比旧的时间戳还小的问题，主要问题出在resetAudioPts。不过也有可能是我进行了改造造成的，可以参考一下。 @yrom

**Comment by kimonic** [comment]
这个问题怎么解决?
java.lang.IllegalStateException: writeSampleData returned an error
	at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
	at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:714)
	at com.hisense.screenrecord.recorder.ScreenRecorder.writeSampleData(ScreenRecorder.java:446)
	at com.hisense.screenrecord.recorder.ScreenRecorder.muxVideo(ScreenRecorder.java:290)
	at com.hisense.screenrecord.recorder.ScreenRecorder.access$500(ScreenRecorder.java:59)
	at com.hisense.screenrecord.recorder.ScreenRecorder$2.onOutputBufferAvailable(ScreenRecorder.java:541)
	at com.hisense.screenrecord.recorder.BaseEncoder$1.onOutputBufferAvailable(BaseEncoder.java:197)
	at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1706)
	at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1653)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)
